### ISSUE TITLE
[Question] Is there a way to reset the state for a sub-module?

### ISSUE THREAD

**Issue by thedelk** [huybuidac/vuex-extensions#13]
I have a store with several modules and only need one of them reset without resetting the entire store. 

I've tried calling `this.reset()` in the sub-module, but a quick look at the console tells me that that is clearly not how to do it.

Can this be done using this package?

**Comment by huybuidac** [comment]
`this.reset` will resetting the entire store.
Sorry, if the function naming makes you confuse.

> Is there a way to reset the state for a sub-module?

It is really hard to making build-in feature. Instead, I provided a function to retrieve the initial module value - `getInitialModuleState`. You can use with `mixins` to enhance.

It is being beta version:
- Installing by: `npm i vuex-extensions@1.1.0-beta` 
- [README](https://github.com/huybuidac/vuex-extensions/blob/local-reset/README.md#get-initial-module-state)
- [unit-test](https://github.com/huybuidac/vuex-extensions/blob/local-reset/tests/unit/store-getInitialModuleState.spec.js#L63)

**Comment by huybuidac** [comment]
@thedelk I have added `option` to `store.reset` at #15 

could you check it?
- Installing by: `npm i vuex-extensions@1.1.1-beta`
- unit-test: https://github.com/huybuidac/vuex-extensions/blob/8041a8eeac177f225f141ae5d560a237771091c0/tests/unit/store-reset.spec.js#L215
- the implementation will look like:
```js
store.reset({
    includes: [ 'moduleA' ]
})
```

**Comment by thedelk** [comment]
Thanks for the quick turnaround! I'll test this out later today and report back.

**Comment by thedelk** [comment]
Sorry for the delay!

I've given it a few test runs and have come to at least one of a few conclusions:

- I'm not configuring it correctly (which is probably my own fault, because for a little while I wasn't looking at the latest commit).
- The fact that I'm using [Vuex-Pathify](https://github.com/davestewart/vuex-pathify) to automate most of my actions and mutations is playing a part somewhere when the store is created. I'll admit my own naivete when it comes to understanding what goes on under the hood.
- My store is nested multiple levels deep, so that adds a layer of complexity to the configuration which is unclear to me.

My store:
```
root
  child1
    grandchild1-1        <--- This is the only one I need reset
  child2
    grandchild2-1
    grandchild2-2
  child3
    grandchild3-1
```

Let me know what you think, and I'll keep working at it to see if I can give you some useful feedback.

Thank you for the quick turnaround!

**Comment by huybuidac** [comment]
Thank for your feedback.
```
root
  child1
    grandchild1-1        <--- This is the only one I need reset
    grandchild1-2
  child2
    grandchild2-1
    grandchild2-2
  child3
    grandchild3-1
```

For grandchild module: you can pass option like that:
```js
store.reset({
    includes: [ { name: 'child1', nested: ['grandchild1-1'] } ]
})
```

and the result as:
```
root
  child1                 <--- if child1 has own state, it is also reseted
    grandchild1-1        <--- reset
    grandchild1-2        <--- keep
  child2
    grandchild2-1
    grandchild2-2
  child3
    grandchild3-1
```

Do you want to keep `child1`?

**Comment by huybuidac** [comment]
@thedelk sorry for inconvenient.

I have updated reset option. `{includes, excludes}` is hard to control.

Installing by: `npm i vuex-extensions@1.1.4-beta`

The implementation for your case will look like:
```js
store.reset({
    self: false,
    // nested: false, <- default configuration for all child modules, if it is not set, it will equals `self`
    modules: {
        child1: {
            modules: {
                'grandchild1-1': { self: true }
            }
        }
    }
})
```

```
root
  child1
    grandchild1-1        <--- This is the only one I need reset
    grandchild1-2
  child2
    grandchild2-1
    grandchild2-2
  child3
    grandchild3-1
```

For other cases, you can read the unitest for detail https://github.com/huybuidac/vuex-extensions/blob/20d0808dc093551ee139d90ed539d9f7255ca2bc/tests/unit/store-reset.spec.js#L276

I think it is OK now.

**Comment by huybuidac** [comment]
https://github.com/huybuidac/vuex-extensions/releases/tag/v1.1.5
