### ISSUE TITLE
[Question] More complete example

### ISSUE THREAD

**Issue by BoDonkey** [huybuidac/vuex-extensions#21]
I can see how to trigger a reset using a button, but can you provide a full example, not quite so abstracted as the code in your README showing how we could use this extension to reset our store when all windows are closed? I'm using this in electron + Vue so I'm trying to clean out the store for each time the user starts the app.

**Comment by huybuidac** [comment]
Sorry for late.

> how we could use this extension to reset our store when all windows are closed? 

In normal, Store will be destroyed after closing window.
You might use a persist plugin ex: https://github.com/championswimmer/vuex-persist
