### ISSUE TITLE
[Question] Can this be used with vuex-persistedstate?

### ISSUE THREAD

**Issue by clustersnake** [huybuidac/vuex-extensions#26]
Hi, I'm currently using vuex-extensions and I just love it but I found a little issue while working with vuex-persistedstate. When I use reset() the state in memory gets cleared but the local/session storage keeps the data, do you think a way to clear the persisted state too?

**Comment by huybuidac** [comment]
vuex-persistedstate lib subscribes store (mutation only), then saves state to storeage. It doesn't catch [replaceState](https://github.com/vuejs/vuex/blob/dev/src/store.js#L197) event.

I think: you can fix it quickly by dispatching an empty mutation at root level after `this.reset`

**Comment by clustersnake** [comment]
Yeah, I figured out that interacting with the session / local storage wasn't vuex-extensions  resposibility. I just combined reset with removeItem but I will try your solution. Thank you very much. Did I say that I love your plugin? 'cause I do. Good job bro.
