### ISSUE TITLE
reset will trigger unwanted watchers

### ISSUE THREAD

**Issue by alvaroenoht** [huybuidac/vuex-extensions#29]
If I use it from a store module, like this, 
`this.reset({
   self: false,
   nested: false,
      modules: { 
        child:{
           self:true,
	},
}
})`

it will trigger watchers of other modules.
-
When resetting one module, the others should be left untouched, but unwanted things happen when resetting only one module. 

-

**Comment by huybuidac** [comment]
@alvaroenoht I made an unit test for it, but I don't see your issue. Can you check again?

https://github.com/huybuidac/vuex-extensions/pull/30/files

**Comment by huybuidac** [comment]
@alvaroenoht I'd like close the issue, if you still have any problem on this, let's fell free to reopen.
