### ISSUE TITLE
Util.js parsed production build bundle size is really large

### ISSUE THREAD

**Issue by ux-engineer** [huybuidac/vuex-extensions#37]
Inspecting production bundle size with webpack-bundle-analyzer shows that util.js has statics size of 1.77KB, however, parsed size 796.29KB (!?). That is 80% of the size of Bootstrap-Vue library.

**Comment by huybuidac** [comment]
really!? It's just a normal js file @@ Hmm, let me check

**Comment by ux-engineer** [comment]
Yes it looks weird as statical size is just 1.77KB but parsed size is huge.

**Comment by huybuidac** [comment]
@ux-engineer sorry for late, I checked, but the parsed size is 674B only.

![image](https://user-images.githubusercontent.com/7322305/104894531-6a22ad00-59a7-11eb-9fce-99cb94c0da80.png)
