### ISSUE TITLE
Is there an option to use vuex-extentions in vuex modules?

### ISSUE THREAD

**Issue by FedorOvchinnikov** [huybuidac/vuex-extensions#38]
I have to use _nested modules_ in my _Vuex store_ and register them dynamically using _registerModule_ function. So i am able to use mixins to my _Vuex store_, but is there a possibility to use it for _nested modules_ like this?

```
let module_mixin
{
    state:
    {
        data: "nested module data",
    },

    mutations:
    {
        set_data: function(state, new_data)
        {
            state.data = new_data
        }
    },
}

let nested_module
{
    mixins: module_mixin,
}

let store = new Vuex.Store({})
store.registerModule('nested_module', nested_module)
```

**Comment by FedorOvchinnikov** [comment]
I needed to read the documentation in more properly I have to close my issue.

**Comment by huybuidac** [comment]
@FedorOvchinnikov I had unit test for runtime module. You can check it:

https://github.com/huybuidac/vuex-extensions/blob/master/tests/unit/store-mixins.spec.js#L113
