### ISSUE TITLE
[Question] Access variables of namespaces modules in mixins

### ISSUE THREAD

**Issue by 5knnbdwm** [huybuidac/vuex-extensions#44]
Hey,

I used the mixins for my getters/mutations without any problem, but now I'm trying to translate my actions to mixins as the structure of a number of actions is the same between a number of modules. The only difference between them is path information. 

Now my problem is that I can't access variables that I defined in the namespaces module from within the mixins.

**Comment by huybuidac** [comment]
@5knnbdwm sorry for late. I created a unit test, and don't get any problem.

Can you make a sample code?

**Comment by 5knnbdwm** [comment]
Hey, so I made a [sample repo](https://github.com/5knnbdwm/test-vuex-mixin) which does contain the problem I'm facing. 

And the situation boils down to the mixins not being able to access local variables in the modules. Now I don't know whether that is `intended` or just a `limitation` that cannot be solved as for the mixins the getters are just translated to the regarding to the available modules.

I'm thinking about simply putting the configuration into the state of the modules and leaving it at that.

**Comment by huybuidac** [comment]
@5knnbdwm I saw the sample, this belongs is JS scope issue. You can't access variable outside scope.

I don't know what exactly you want. But if you want dynamic path, you check the unit test:
- https://github.com/huybuidac/vuex-extensions/pull/45/files
- ` store.getters['sub/getState']('count')`

**Comment by 5knnbdwm** [comment]
Okay thanks for the example. That did help in my case.
