### ISSUE TITLE
[FR] Vuex 4 Support

### ISSUE THREAD

**Issue by wenfangdu** [huybuidac/vuex-extensions#52]
Please add Vuex 4 support 🙏.

**Comment by huybuidac** [comment]
@wenfangdu very sorry for late. I push v4.0.0 beta. Can you try and feedback?

https://www.npmjs.com/package/vuex-extensions/v/4.0.0-beta

**Comment by wenfangdu** [comment]
@huybuidac Could you please add a Vuex 4 store reset example on ReadMe?

**Comment by huybuidac** [comment]
@wenfangdu I'm preparing document and example.
1. For composition: const store = useStore(); store.reset()
2. For normal component: this.$store.reset()

**Comment by wenfangdu** [comment]
@huybuidac How to do the registering, since [Vuex 4 installation process has changed](https://next.vuex.vuejs.org/guide/migrating-to-4-0-from-3-x.html#installation-process) to using `createStore`, which `vuex-extensions` happen to use as well.

**Comment by huybuidac** [comment]
@wenfangdu createStore function from vuex just wrap `new Store(options)` https://github.com/vuejs/vuex/blob/7151622d646968686546f1c4c80f7575c9b99176/src/store.js#L15

`vuex-extensions` v4 works normal with current registering https://github.com/huybuidac/vuex-extensions#creating-vuexstore

```js
import Vuex from 'vuex'
import { createStore } from 'vuex-extensions'

export default createStore(Vuex.Store, {
  plugins: []
  modules: {}
})
```

**Comment by wenfangdu** [comment]
@huybuidac Thanks! I just tried it out, works so far. I suggest changing the registration bit from :

```js
import Vuex from 'vuex'
import { createStore } from 'vuex-extensions'

export default createStore(Vuex.Store, {})
```

To:

```js
import { Store } from 'vuex'
import { createStore } from 'vuex-extensions'

export default createStore(Store, {})
```

If I'm not mistaken using default import here increased bundled size?

```js
export default {
  Store,
  install,
  version: '__VERSION__',
  mapState,
  mapMutations,
  mapGetters,
  mapActions,
  createNamespacedHelpers,
  createLogger
}

export {
  Store,
  install,
  mapState,
  mapMutations,
  mapGetters,
  mapActions,
  createNamespacedHelpers,
  createLogger
}
```

[Source](https://github.com/vuejs/vuex/blob/3ba884b9b3203a4f378ef7fc837e1bc48aa6b29e/src/index.js#L5)

**Comment by huybuidac** [comment]
@wenfangdu good. Both are OK but destructuring import is better

```js
import { Store } from 'vuex'
import { createStore } from 'vuex-extensions'

export default createStore(Store, {})
```
