### ISSUE TITLE
TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Kenvdb** [huybuidac/vuex-extensions#60]
**Describe the bug**
- Getting an error when calling this.$store.reset();

`vuexStoreClass.prototype.reset = function (options) {
   var originalState = getOriginalState(this._modules.root, (0, _util.deepCopy)(this._state.data), options);
   this.replaceState((0, _util.deepCopy)(originalState));
};`

_vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "$route": "TypeError: Cannot read property 'data' of undefined"_

**Installed version:** 
"vuex-extensions": "^4.0.0"

**Expected behavior**
- Resetting to initial state of the Vuex Store

**Comment by huybuidac** [comment]
@Kenvdb what version of vuex are you using?

vuex-extensions v4 is used for vuex 4

**Comment by Kenvdb** [comment]
Ah oke, I'm currently using version 3.6. Thanks for your quick reply?

Another question, is it also possible to reset all (module) states, except for one, without declaring all the modules?

**Comment by huybuidac** [comment]
@Kenvdb yes, possible. something like this
```
this.$store.reset({ 
  modules: { 
    child1: {
      self: false
    } 
  }
})
```

**Comment by Kenvdb** [comment]
Thanks for your awesome & quick support!
