### ISSUE TITLE
Javascript Set in state

### ISSUE THREAD

**Issue by Elaskin** [huybuidac/vuex-extensions#95]
**Describe the bug**
- if state includes javascript Set when state is reset, field becomes Object

**Expected behavior**
- field resets to initial Set

error occures because of this line (utils.js:50)
![image](https://github.com/huybuidac/vuex-extensions/assets/33493232/f0b7d39a-5d76-409c-9215-f83a3d12d1b7)

**Comment by huybuidac** [comment]
@Elaskin I have fixed this, you can try on v1.2.2 for vue2 or v.4.1.0 for vue3

**Comment by Elaskin** [comment]
Thanks, is there a reason against structuredClone though?

**Comment by huybuidac** [comment]
> Thanks, is there a reason against structuredClone though?

Yes, I used vuex util to clone `https://github.com/vuejs/vuex/blob/main/src/util.js`

It does not support Set, Map ... I have changed to other clone mechanism

**Comment by Elaskin** [comment]
> > Thanks, is there a reason against structuredClone though?
> 
> Yes, I used vuex util to clone `https://github.com/vuejs/vuex/blob/main/src/util.js`
> 
> It does not support Set, Map ... I have changed to other clone mechanism

I meant why not just use https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

**Comment by huybuidac** [comment]
> I meant why not just use https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

You can check it, the function requires recent versions of browser and node: https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility

Plain js is usually better approach.
